# Generated by Django 4.0.3 on 2022-06-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(null=True),
        ),
    ]
